tinymce.addI18n('en.filery', {
    'Delete': 'Delete',
    'Select': 'Select',
    'File manager': 'Dateiverwaltung',
    'Are you sure you want to delete the file "{0}"?': 'Are you sure you want to delete the file "{0}"?',
    'Upload file': 'Upload file',
    'Select file': 'Select file',
    'Insert as link': 'Insert as link',
    'Insert as image': 'Insert as image',
    'Upload failed: {0}': 'Upload failed: {0}',
    'Upload failed': 'Upload failed',
    'Delete failed': 'Delete failed',
    '"{0}" successfully uploaded': '"{0}" successfully uploaded',
    '"{0}" successfully deleted': '"{0}" successfully deleted',
    '"{0}" successfully inserted': '"{0}" successfully inserted',
    '"{0}" as image successfully inserted': '"{0}" as image successfully inserted',
    '"{0}" as link successfully inserted': '"{0}" as link successfully inserted',
});